services:
  - type: web
    name: network-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "./backend/start.sh"
    envVars:
      - key: FLASK_ENV
        value: production


# services:
#   - type: web
#     name: network-backend
#     env: python
#     plan: free
#     buildCommand: "pip install -r backend/requirements.txt"
#     startCommand: "./backend/start.sh"
#     envVars:
#       - key: FLASK_ENV
#         value: production

# staticSites:
#   - name: network-frontend
#     staticPublishPath: frontend/build
#     buildCommand: npm run build
#     envVars:
#       - key: REACT_APP_API_URL
#         value: https://network-backend.onrender.com

